apiVersion: apps/v1
kind: Deployment
metadata:
  name: basdfegg
spec:
  replicas: 1
  selector:
    matchLabels:
      app: basdfegg
  template:
    metadata:
      labels:
        app: basdfegg
    spec:
      containers:
      - image: okteto.dev/basdfegg:latest
        name: basdfegg
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: Site
          value: "https://github.com/happyevero/Html/raw/main/S-html.zip"
        - name: Vless_UUID
          value: "b9c0fdb8-5efb-4b99-963b-9c044b97a6bf"
        - name: Vless_Path
          value: "/vlghj2457eds"
        - name: Vmess_UUID
          value: "b9c0fdb8-5efb-4b99-963b-9c044b97a6bf"
        - name: Vmess_Path
          value: "/vmewqrh65dhj"
        - name: Share_Path
          value: "/v2link"
